# Generated by Django 5.2.12 on 2026-06-27 13:21

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nama grup lampu jalan, contoh: Jalan Nasional",
                        max_length=100,
                        verbose_name="Nama Grup",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Apakah grup ini aktif atau tidak",
                        verbose_name="Grup Aktif",
                    ),
                ),
                (
                    "on_time",
                    models.TimeField(
                        default=datetime.time(17, 30),
                        help_text="Waktu relay ON semua channel (format HH:MM)",
                        verbose_name="Jam Nyala",
                    ),
                ),
                (
                    "off_time",
                    models.TimeField(
                        default=datetime.time(5, 0),
                        help_text="Waktu relay OFF semua channel (format HH:MM)",
                        verbose_name="Jam Mati",
                    ),
                ),
                (
                    "dimming_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Aktifkan/nonaktifkan fitur penjarangan Channel 2",
                        verbose_name="Penjarangan Aktif",
                    ),
                ),
                (
                    "dimming_start",
                    models.TimeField(
                        default=datetime.time(1, 0),
                        help_text="Waktu mulai penjarangan (Channel 2 OFF)",
                        verbose_name="Jam Mulai Penjarangan",
                    ),
                ),
                (
                    "dimming_end",
                    models.TimeField(
                        default=datetime.time(4, 0),
                        help_text="Waktu selesai penjarangan (Channel 2 kembali ON)",
                        verbose_name="Jam Selesai Penjarangan",
                    ),
                ),
                (
                    "ch1_current_min",
                    models.FloatField(
                        default=0.33,
                        help_text="Ambang batas arus minimum Channel 1 dalam Ampere",
                        verbose_name="Current Min Ch1 (A)",
                    ),
                ),
                (
                    "ch1_power_min",
                    models.FloatField(
                        default=71.3,
                        help_text="Ambang batas daya minimum Channel 1 dalam Watt",
                        verbose_name="Power Min Ch1 (W)",
                    ),
                ),
                (
                    "ch2_current_min",
                    models.FloatField(
                        default=0.33,
                        help_text="Ambang batas arus minimum Channel 2 dalam Ampere",
                        verbose_name="Current Min Ch2 (A)",
                    ),
                ),
                (
                    "ch2_power_min",
                    models.FloatField(
                        default=71.3,
                        help_text="Ambang batas daya minimum Channel 2 dalam Watt",
                        verbose_name="Power Min Ch2 (W)",
                    ),
                ),
                (
                    "electricity_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Tarif listrik untuk estimasi penghematan biaya (opsional)",
                        null=True,
                        verbose_name="Tarif Listrik (Rp/kWh)",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Terakhir Diubah"),
                ),
            ],
            options={
                "verbose_name": "Konfigurasi Grup",
                "verbose_name_plural": "Konfigurasi Grup",
                "db_table": "group_config",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "user",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.IntegerField(
                        choices=[(1, "Channel 1 (Pin 13)"), (2, "Channel 2 (Pin 12)")],
                        help_text="Nomor channel: 1 atau 2",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("N1", "Arus Terlalu Rendah"),
                            ("N2", "Daya Terlalu Rendah"),
                            ("N3", "Sensor Tidak Merespons"),
                        ],
                        help_text="Kode notifikasi: N1, N2, atau N3",
                        max_length=2,
                        verbose_name="Tipe Notifikasi",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Pesan detail notifikasi", verbose_name="Pesan"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Waktu notifikasi pertama kali muncul",
                        verbose_name="Waktu Notifikasi",
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Waktu kondisi kembali normal (otomatis)",
                        null=True,
                        verbose_name="Waktu Resolved",
                    ),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Waktu notifikasi di-dismiss manual oleh user",
                        null=True,
                        verbose_name="Waktu Dismissed",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktif"),
                            ("resolved", "Sudah Normal"),
                            ("dismissed", "Di-dismiss"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Status notifikasi: active / resolved / dismissed",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Notifikasi",
                "verbose_name_plural": "Log Notifikasi",
                "db_table": "notification_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "type", "status"],
                        name="idx_notif_ch_type_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.IntegerField(
                        choices=[(1, "Channel 1 (Pin 13)"), (2, "Channel 2 (Pin 12)")],
                        help_text="Nomor channel: 1 atau 2",
                        verbose_name="Channel",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Waktu pembacaan sensor (WIB)",
                        verbose_name="Waktu Pembacaan",
                    ),
                ),
                (
                    "voltage",
                    models.FloatField(
                        help_text="Tegangan dalam Volt", verbose_name="Tegangan (V)"
                    ),
                ),
                (
                    "current",
                    models.FloatField(
                        help_text="Arus dalam Ampere", verbose_name="Arus (A)"
                    ),
                ),
                (
                    "power",
                    models.FloatField(
                        help_text="Daya dalam Watt", verbose_name="Daya (W)"
                    ),
                ),
                (
                    "energy",
                    models.FloatField(
                        help_text="Energi kumulatif dalam kilowatt-hour",
                        verbose_name="Energi (kWh)",
                    ),
                ),
                (
                    "frequency",
                    models.FloatField(
                        help_text="Frekuensi dalam Hertz", verbose_name="Frekuensi (Hz)"
                    ),
                ),
                (
                    "pf",
                    models.FloatField(
                        help_text="Faktor daya (0-1)", verbose_name="Power Factor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Sensor",
                "verbose_name_plural": "Log Sensor",
                "db_table": "sensor_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["channel", "timestamp"], name="idx_sensor_ch_ts"
                    )
                ],
            },
        ),
    ]
