# Generated by Django 5.2.12 on 2026-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupconfig",
            name="electricity_rate",
        ),
        migrations.AddField(
            model_name="groupconfig",
            name="data_send_interval",
            field=models.IntegerField(
                default=5,
                help_text="Interval jeda untuk ESP32 mengirim data ke server",
                verbose_name="Jeda Waktu Pengiriman Data (Detik)",
            ),
        ),
    ]
