# Generated by Django 5.2.12 on 2026-06-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_groupconfig_electricity_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupconfig",
            name="ch1_power_min",
        ),
        migrations.RemoveField(
            model_name="groupconfig",
            name="ch2_power_min",
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="type",
            field=models.CharField(
                choices=[
                    ("N1", "Arus Terlalu Rendah"),
                    ("N2", "Sensor Tidak Merespons"),
                ],
                help_text="Kode notifikasi: N1 atau N2",
                max_length=2,
                verbose_name="Tipe Notifikasi",
            ),
        ),
    ]
