# Generated by Django 5.2.12 on 2026-07-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_groupconfig_ch1_power_min_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notificationlog",
            name="idx_notif_ch_type_status",
        ),
        migrations.RemoveIndex(
            model_name="sensorlog",
            name="idx_sensor_ch_ts",
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="group_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Grup konfigurasi lampu jalan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_logs",
                to="app.groupconfig",
                verbose_name="Grup",
            ),
        ),
        migrations.AddField(
            model_name="sensorlog",
            name="group_config",
            field=models.ForeignKey(
                blank=True,
                help_text="Grup konfigurasi lampu jalan",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sensor_logs",
                to="app.groupconfig",
                verbose_name="Grup",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["group_config", "channel", "type", "status"],
                name="idx_notif_grp_ch_type_st",
            ),
        ),
        migrations.AddIndex(
            model_name="sensorlog",
            index=models.Index(
                fields=["group_config", "channel", "timestamp"],
                name="idx_sensor_grp_ch_ts",
            ),
        ),
    ]
